-- PRCDB.ITEM_PRICE : current shelf price per SKU per pricing region
-- Updated in place by PRCUPD01 (UPDATE ... WHERE CURRENT OF PRICE_CSR).
-- Demo stand-in : data/db2/before/ITEM_PRICE.csv -> data/db2/expected_after/ITEM_PRICE.csv
-- DCLGEN        : cobol/copybooks/DCLITMPR.cpy

CREATE TABLE PRCDB.ITEM_PRICE
(
    SKU             CHAR(8)        NOT NULL,
    REGION_CD       CHAR(2)        NOT NULL,
    REG_PRICE       DECIMAL(7, 2)  NOT NULL,
    CURR_PRICE      DECIMAL(7, 2)  NOT NULL,
    PRICE_TYPE      CHAR(1)        NOT NULL WITH DEFAULT 'R',
    PROMO_ID        CHAR(10),
    PROMO_EFF_DT    DATE,
    PROMO_END_DT    DATE,
    LAST_UPD_JOB    CHAR(8)        NOT NULL,
    LAST_UPD_TS     TIMESTAMP      NOT NULL WITH DEFAULT,
    CONSTRAINT PK_ITEM_PRICE PRIMARY KEY (SKU, REGION_CD),
    CONSTRAINT CK_PRICE_TYPE CHECK (PRICE_TYPE IN ('R', 'P', 'C')),
    CONSTRAINT FK_ITEM_PRICE_REGION FOREIGN KEY (REGION_CD)
        REFERENCES PRCDB.PRICE_REGION (REGION_CD)
)
IN PRCDB.TSPRICE
CCSID EBCDIC;

CREATE UNIQUE INDEX PRCDB.XITEM_PRICE_01
    ON PRCDB.ITEM_PRICE (SKU, REGION_CD)
    CLUSTER;

CREATE INDEX PRCDB.XITEM_PRICE_02
    ON PRCDB.ITEM_PRICE (PRICE_TYPE, PROMO_END_DT);

COMMENT ON TABLE PRCDB.ITEM_PRICE IS
    'Current shelf price by SKU and region. PRICE_TYPE R=regular P=promo C=clearance.';
