-- PRCDB.PRICE_REGION / PRCDB.STORE_REGION : pricing region reference data
-- Read-only for PRCUPD01 (store -> region resolution for store-level promos).
-- Demo stand-in : data/input/STORE_REGION.csv (weekly unload, job STRGNUNL)
-- DCLGEN        : cobol/copybooks/DCLSTRGN.cpy

CREATE TABLE PRCDB.PRICE_REGION
(
    REGION_CD       CHAR(2)        NOT NULL,
    REGION_NAME     VARCHAR(30)    NOT NULL,
    CONTIGUOUS_IND  CHAR(1)        NOT NULL WITH DEFAULT 'Y',
    CONSTRAINT PK_PRICE_REGION PRIMARY KEY (REGION_CD)
)
IN PRCDB.TSREF
CCSID EBCDIC;

INSERT INTO PRCDB.PRICE_REGION VALUES ('NE', 'NORTHEAST',              'Y');
INSERT INTO PRCDB.PRICE_REGION VALUES ('SE', 'SOUTHEAST',              'Y');
INSERT INTO PRCDB.PRICE_REGION VALUES ('MW', 'MIDWEST',                'Y');
INSERT INTO PRCDB.PRICE_REGION VALUES ('WC', 'WEST COAST',             'Y');
INSERT INTO PRCDB.PRICE_REGION VALUES ('NC', 'NON-CONTIGUOUS (AK/HI)', 'N');

CREATE TABLE PRCDB.STORE_REGION
(
    STORE_NBR       CHAR(4)        NOT NULL,
    STORE_NAME      VARCHAR(30)    NOT NULL,
    STATE_CD        CHAR(2)        NOT NULL,
    REGION_CD       CHAR(2)        NOT NULL,
    OPEN_DT         DATE,
    CLOSE_DT        DATE,
    CONSTRAINT PK_STORE_REGION PRIMARY KEY (STORE_NBR),
    CONSTRAINT FK_STORE_REGION_RGN FOREIGN KEY (REGION_CD)
        REFERENCES PRCDB.PRICE_REGION (REGION_CD)
)
IN PRCDB.TSREF
CCSID EBCDIC;

CREATE INDEX PRCDB.XSTORE_REGION_01
    ON PRCDB.STORE_REGION (REGION_CD, STORE_NBR);

COMMENT ON TABLE PRCDB.STORE_REGION IS
    'Store to pricing-region mapping. Region NC (Alaska/Hawaii) carries freight uplift rules in PRCRGN01.';
